### PR TITLE
fix config file .env upgrade

### PR DESCRIPTION
**Pull request by nathanael-h**
fix config file .env was not modified not during upgrade neither during change url

## Problem

- I found my nocodb install crashed and with an outdated config file

## Solution

- I saw in code that the template for .env file was updated but the changes were not applied on upgrade and change_url scripts

## PR Status

- [X] Code finished and ready to be reviewed/tested
- [X] The fix/enhancement were manually tested 

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by nathanael-h** [comment]
!testme

**Comment by nathanael-h** [comment]
Hello @tituspijean I saw you worked on this repo, fyi I tested this branch on my ynh instance and it works well :slightly_smiling_face:

**Comment by tituspijean** [comment]
LGTM! I took the liberty of rebasing your branch to testing, to avoid all these merge commits. ;)

**Comment by nathanael-h** [comment]
Yeah I should have done it, sorry, thanks!

**Pull request merged**
