### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by tituspijean**
- [x] Add domain information in environment file
- [x] Increase attachments upload limit
- [x] Upgrade to v0.109.2
- [x] Switch to `production` mode

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by KvL159** [comment]
Thanks @tituspijean ! Uploading up to 100mb is now working!

**Comment by tituspijean** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Review by alexAubin — APPROVED** [review]
LGTM though idk if titus was still planning on iterating on the todo in the initial post

**Pull request merged**
