### PR TITLE
Update env

### LINKED ISSUE #76: Attachments limited to 1mb
### Describe the bug

Attachment are limited to 1mb

### Context
- YunoHost version: Latest
- Using, or trying to install package version/branch: master

### Steps to reproduce

1. Attach an image or pdf over 1mb
2. Get error code 413

From this upstream feedback: https://github.com/nocodb/nocodb/discussions/1135
It appears that nginx limit needs to be updated in docker container ? I'm not familiar enough with docker to investigate further

### PR DESCRIPTION
**Pull request by KvL159**
Closes #76 

## Problem

- Fix attachment upload (see [https://github.com/YunoHost-Apps/nocodb_ynh/issues/72](https://github.com/YunoHost-Apps/nocodb_ynh/issues/72))

## Solution

- Add public url

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [X] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by KvL159** [comment]
By the power of systemd, I invoke The Great App CI to test this Pull Request!

**Comment by tituspijean** [comment]
!testme
(You need to be part of the Yunohost-Apps app organization)

**Comment by KvL159** [comment]
> !testme (You need to be part of the Yunohost-Apps app organization)

Thanks !

**Comment by tituspijean** [comment]
Thank you!

**Pull request merged**
